# ============================================================
# Matrix Dotfiles
# ------------------------------------------------------------
# Author    : Fermin Aroca
# License   : MIT
# ============================================================

brew "bash-completion@2"
brew "git"
brew "jq"
brew "shellcheck"
brew "vim"
